AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ServiceName:
    Type: String
  EnvironmentNameLower:
    Type: String
  EnvironmentNameUpper:
    Type: String

Resources:
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
        - AttributeName: "EventSeq"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "Id"
          KeyType: "HASH"
        - AttributeName: "EventSeq"
          KeyType: "RANGE"
      TableName: !Sub "${EnvironmentNameLower}-${ServiceName}-event-store-ddb"
  EffectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Id"
          KeyType: "HASH"
      TableName: !Sub "${EnvironmentNameLower}-${ServiceName}-effects-store-ddb"
  IdentityTable:
    Type: AWS::DynamoDB::Table
    Properties:
     BillingMode: PAY_PER_REQUEST
     AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
     KeySchema:
        - AttributeName: "Id"
          KeyType: "HASH"
     TableName: !Sub "${EnvironmentNameLower}-${ServiceName}-identity-store-ddb"

Outputs:
  DatabaseName:
    Value: !Ref EventsTable

